swagger: "2.0"

info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
  
host: localhost:8085

schemes:
  - http
  
paths:
  /solve:
    post:
      operationId: app.sum_up_all_elements
      consumes:
        - applitcation/json
      parameters:
        - in: body
          name: json_info
          schema:
            type: object
            required:
              - calc_id
              - elements
            properties:
              calc_id:
                type: string
              elements:
                type: array
                items:
                  type: integer
      produces:
        - application/json
      responses:
        200:
          description: Success
          schema:
            type: object
            properties:
              error:
                type: string
                description: Error description
              scenario_id:
                type: string
                description: Scenario ID
      
    
